### ISSUE TITLE
deckem on node v0.6.10

### ISSUE THREAD

**Issue by nopper** [DamonOehlman/deckem#3]
I am trying to use deckem on top of node 0.6.10 but it seems to not be working. After the installation through `npm install deckem -g` if I tried to execute it but what I got was the following output:

```
» deckem
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function (targetModule) {
    return new Scaffolder(targetModule);
} has no method 'create'
    at Object.<anonymous> (/home/nopper/.nvm/v0.6.10/lib/node_modules/deckem/bin/deckem:4:34)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

Instead, if I try to use the git version I get an error about a missing `cleave` module which seems to not be avaiable anymore through `npm`.

**Comment by DamonOehlman** [comment]
Thanks for letting me know - I'll have a look at that now.

**Comment by DamonOehlman** [comment]
Hey Mate,

I've just updated the code in github and also pushed an updated version (`0.0.11`) to NPM.  It's still in a bit of a transitional stage though given I've changed around a few of the underlying libraries, but I'll try to have a look at that over the next couple of days.

Cheers,
Damon.
